# Generated by Django 3.2.16 on 2023-07-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_auto_20230103_0709'),
        ('tasks', '0039_annotation_draft_created_at'),
    ]

    operations = [
    ]
