# Generated by Django 3.2.20 on 2023-11-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_merge_0034_auto_20230103_0709_0040_auto_20230628_1101'),
        ('tasks', '0044_auto_20230907_0155'),
    ]

    operations = [
    ]
