# Generated by Django 3.2.20 on 2023-11-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20231103_0020'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['pinned_at', 'created_at'], name='project_pinned__a39ccb_idx'),
        ),
    ]
